# Generated by Django 3.1.6 on 2025-11-24 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('Password', models.IntegerField()),
                ('Confirm', models.IntegerField()),
                ('Role', models.CharField(default='user', max_length=15)),
            ],
        ),
    ]
