# Generated by Django 3.1.6 on 2025-11-24 13:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='My_Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, default='', max_length=50)),
                ('phone', models.CharField(blank=True, default='', max_length=25)),
                ('city', models.CharField(blank=True, default='', max_length=25)),
                ('pincode', models.IntegerField(default='455001')),
                ('date', models.DateTimeField(default=datetime.datetime.today)),
            ],
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
