# Generated by Django 3.1.6 on 2025-12-02 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_auto_20251124_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='my_order',
            name='razor_pay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='my_order',
            name='razor_pay_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='my_order',
            name='razor_pay_signature',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
