# Generated by Django 3.1.6 on 2025-12-02 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_auto_20251202_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='my_order',
            name='razor_pay_order_id',
        ),
        migrations.RemoveField(
            model_name='my_order',
            name='razor_pay_payment_id',
        ),
        migrations.RemoveField(
            model_name='my_order',
            name='razor_pay_signature',
        ),
    ]
